name: SCA - OWASP Dependency Check

on:
  push:
    branches: [ "main", "master" ]

jobs:
  analyze:
    name: Analyze Dependencies
    runs-on: ubuntu-latest
    
    steps:
      # 1. Lấy code về
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Chạy tool quét ngay lập tức (Không cài Java để tránh lỗi xung đột)
      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'microShop'
          path: '.'
          format: 'HTML'
          out: 'reports'
          # Bỏ qua quét node_modules nếu dự án có lẫn JS để chạy nhanh hơn
          args: >
            --enableExperimental
            --disableAssembly
          
      # 3. Lưu báo cáo
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: Dependency-Check-Report
          path: reports/dependency-check-report.html
